
name: Build CharmJoinMessage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore packages
        run: nuget restore CharmJoinMessage.csproj

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build plugin
        run: msbuild "CharmJoinMessage.csproj" /p:Configuration=Release /p:Platform="Any CPU" /t:Build /p:OutputPath=bin\Release\ /v:minimal
